[[cap_colaboracao]]
== Construção Colaborativa dos livros

Versão online:: https://github.com/edusantana/guia-geral-ead-computacao-ufpb/blob/master/livro/capitulos/guia-colaboracao.adoc

(((Colaboração)))

Gostaria de ressaltar o aspecto mais
importante dele: *o sucesso e confiança deste guia depende de VOCÊ,
da sua Colaboração*.

Este documento foi concebido para ser uma *produção colaborativa*,
onde todos os envolvidos com o curso possam enviar suas contribuições
para mantê-lo atualizado e útil.

=== Como você pode contribuir com o Guia

(((Guia, Colaboração)))

Lendo o guia e solicitando atualizar o guia::
Após ler o guia você percebe que faltou explicação de algum conteúdo,
então você pode ir em
https://github.com/edusantana/guia-geral-ead-computacao-ufpb/issues/new e
escrever qual a contribuição que está faltando, exemplo:
+
....

Na seção "Dispensa de Disciplina", ficou faltando informar
se o aluno deve cursar a disciplina enquanto o processo de
dispensa ainda está sendo executado.

....

Discutindo as solicitações::
Você pode consultar as solicitações em
https://github.com/edusantana/guia-geral-ead-computacao-ufpb/issues e
participar das discussões nas solicitações:

Atualizando o guia::
Neste caso você pode atualizar os arquivos de texto do guia em
https://github.com/edusantana/guia-geral-ead-computacao-ufpb/tree/master/livro/capitulos.
Depois de atualizado você envia um Pull Request e aguarda que sua
alteração seja incorporada ao Guia.

==== Para acessar o Guia on-line

(((Guia, Acesso)))

Diretamente no repositório:: https://github.com/edusantana/guia-geral-ead-computacao-ufpb

=== Conferência gravada sobre o Guia e a Produção dos livros

(((Guia, Conferência)))


Link da conferência gravada:: http://webconf2.rnp.br/p54ogecb8jk/

.CONTEÚDOS DA CONFERÊNCIA
....
= Apresentação do Guia Geral do Curso
== Guia dos Alunos
== Guia dos Tutores
== Guia dos Professores
== Guia dos Polos
== Construção colaborativa dos Guias
= Onde encontrar os livros do curso
== Como baixar todos os livros de uma única vez (releasess)
== Como acessar os livros individualmente (releases e repositórios)
== Como acessar as versões em produção dos livros (instáveis)
== Como ser notificado de novas atualizações dos livros
= Como os alunos do curso podem contribuir com os livros
== Criando uma conta no github
== Indicando correções/erros/sugestões (Issue)
== Submetendo correções (Pull Request)
= Como os livros são produzidos
....

////
Sempre termine os arquivos com uma linha em branco.
////
