== Contribuindo com os Livros do Curso

Versão online:: https://github.com/edusantana/guia-geral-ead-computacao-ufpb/blob/master/livro/capitulos/livros-contribuicao.adoc

(((Livros, Contribuição)))

Nós incentivamos nossos alunos a contribuirem com melhorias
para material didático do curso. Encontrou algum erro no *livru*?
Fale pra gente!

Nesta seção será apresentado:

* Requisitos para contribuição
* Como contribuir com os livros
* Escolhendo um livro para contribuir
* Métodos avançados de contribuição


=== Requisitos para contribuição

Todos os livros que produzimos estão armazenados no
https://github.com[github]. 

[IMPORTANT]
====
*É necessário criar um login (_sign up_)
no github para poder realizar contribuições*. 

Link para criar uma login/conta no github acesse https://github.com/join
====

TIP: Depois que você criou uma conta de usuário, recomendo realizar o
*logout* para aprender a fazer o *login*.
Faça o logout acessando https://github.com/logout.

Entre em https://github.com e faça o *login* (_sign in_).

A criação da conta é o único requisito para contribuir com os livros.

==== Por que utilizar o github para receber?

O github possui um recurso chamado *issues*, que se assemelha a 
um número de protocolo de atendimento. Ao criar um issue 
(ex: https://github.com/edusantana/guia-geral-ead-computacao-ufpb/issues/8[#8])
especificamos os detalhes dele. O issue fica em aberto, aguardando antedimento,
todos os encaminhamentos sobre ele ficarão registrados nele.

Quando uma contribuição (_issue_) é cadastrada, você e todos os
envolvidos na produção do livro poderão discutir sobre ela. Todos
os envolvidos com o livro, e você, serão notificados a cada
nova postagem na discussão do issue, inclusive sua resolução.

Através dos issues podemos monitorar quais solicitações recebam atenção e 
em que estados elas estão.


=== Enviando contribuição através do link no final dos capítulos

Nas novas versões dos nossos livros, ao final de cada capítulo encontramos
uma caixa em que o leitor é incentivado a realizar um feedback sobre o capítulo.
Ao clicar no link indicado, o aluno é direcionado ao repositório específico 
do livro que está lendo. Neste caso, a página aberta já preenchida
com as informações do capítulo e versão do livro que o aluno estava acessando.
Adicione os detalhes do seu feedback e clique em `Submit`.

NOTE: Este é o método preferencial para submissão de feedback, uma
vez que ele já preenche as informações do capítulo e versão do livro
que está sendo utilizado, além de ser prático.

=== Como pode ser uma contribuição?

Uma contribuição pode consistir apenas em *o que* precisa ser
modificado e *onde*. Você pode utilizar o texto a seguir para compor
sua contribuição:

.Título da contribuição/feedback
....

*Erro*:

> Indique o erro aqui.

*Localização do erro*: Capítulo X, pág Y, versão `v?.?.?`.

*Correção*:

Indique correção/sugestão aqui.

....

TIP: Ao compor mensagens no github você pode utilizar as formatações
do https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet[Markdown].


=== Escolhendo um livro para contribuir

Os links a seguir são para criação de um _issue_ nos livros do curso,
escolha qual o livro que deseja deixar sua contribuição:

Este guia: +
https://github.com/edusantana/guia-geral-ead-computacao-ufpb/issues/new

Período 1: +
https://github.com/edusantana/fundamentos-socio-historico-da-educacao-livro/issues/new +
https://github.com/edusantana/introducao-a-computacao-livro/issues/new +
https://github.com/edusantana/introducao-a-ead-livro/issues/new +
https://github.com/edusantana/introducao-a-programacao-livro/issues/new +
https://github.com/edusantana/matematica-elementar-livro/issues/new +

Período 2: +
https://github.com/edusantana/calculo-diferencial-e-integral-livro/issues/new +
https://github.com/edusantana/fundamentos-psicologicos-da-educacao-livro/issues/new +
https://github.com/edusantana/linguagem-de-programacao-i-livro/issues/new +
https://github.com/edusantana/metodologia-do-trabalho-cientifico-livro/issues/new +

Período 3: +
https://github.com/edusantana/estruturas-de-dados-livro/issues/new +
https://github.com/edusantana/introducao-a-arquitetura-de-computadores-livro/issues/new +
https://github.com/edusantana/matematica-computacional-livro/issues/new +

Período 4: +
https://github.com/edusantana/estatistica-livro/issues/new


=== Métodos avançados de contribuição

* https://help.github.com/[baixar o livro utilizando o git]
* alterar o código/texto do livro
* realizar um pull request com as alterações

=== Seções relacionadas

* https://github.com/edusantana/guia-geral-ead-computacao-ufpb/blob/master/livro/capitulos/livros.asc[livros.asc]
* https://github.com/edusantana/guia-geral-ead-computacao-ufpb/blob/master/livro/capitulos/links-para-baixar-os-livros.txt[links-para-baixar-os-livros.txt]

////
Sempre termine os arquivos com uma linha em branco.
////
